### PR TITLE
[WIP] create wireframes

### PR DESCRIPTION
**Pull request by simiyu1**
#### What does this PR do?
Show Mockup Designs
Add designs to readme

#### Description of Task to be completed?

Design layout of the entry screen and activity screen

How should this be manually tested?

On opening the branch, the readme shows images of the mockups. A live version can be found at this [Balasmiq URL](https://balsamiq.cloud/s9lpfm3/pmmi48r)

#### What are the relevant pivotal tracker stories?
[#158792524](https://www.pivotaltracker.com/story/show/158792524)

#### Questions:
Will I need to create one commit for every day or only one commit for the entire app?

### CODE REVIEW

**Comment by Rwothoromo** [comment]
@simiyu1 The `Balasmiq URL` is not working. Also, could you make the pivotal tracker story #158792524 a link?

**Comment by simiyu1** [comment]
> @simiyu1 The `Balasmiq URL` is not working. Also, could you make the pivotal tracker story #158792524 a link?

Resolved

**Comment by Rwothoromo** [comment]
@simiyu1 Great job with the designs. However, could you make the user icon and the details fit in one card rather than two items lying side by side?

Also on the readme, could you align the images side by side?
We can merge this thereafter.

**Comment by Rwothoromo** [comment]
@simiyu1 Concerning commits, one atomic commit will do for each PR based off the PT stories.

**Pull request merged**
